// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameExerciseMaterial = "exercise_material"

// ExerciseMaterial mapped from table <exercise_material>
type ExerciseMaterial struct {
	ID        int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Content   string     `gorm:"column:content;not null" json:"content"`
	ImagePath *string    `gorm:"column:image_path" json:"image_path"`
	CreatedAt *time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName ExerciseMaterial's table name
func (*ExerciseMaterial) TableName() string {
	return TableNameExerciseMaterial
}
