// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameExerciseQuestion = "exercise_question"

// ExerciseQuestion mapped from table <exercise_question>
type ExerciseQuestion struct {
	ID          int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MaterialID  int32      `gorm:"column:material_id;not null" json:"material_id"`
	Question    string     `gorm:"column:question;not null" json:"question"`
	Answer      string     `gorm:"column:answer;not null" json:"answer"`
	Explanation *string    `gorm:"column:explanation" json:"explanation"`
	CreatedAt   *time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName ExerciseQuestion's table name
func (*ExerciseQuestion) TableName() string {
	return TableNameExerciseQuestion
}
