// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameImageOcrTask = "image_ocr_tasks"

// ImageOcrTask mapped from table <image_ocr_tasks>
type ImageOcrTask struct {
	ID            int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ImageURL      string     `gorm:"column:image_url;not null" json:"image_url"`
	Cookie        *string    `gorm:"column:cookie" json:"cookie"`
	Referer       *string    `gorm:"column:referer" json:"referer"`
	LocalFilePath *string    `gorm:"column:local_file_path" json:"local_file_path"`
	OcrResult     *string    `gorm:"column:ocr_result" json:"ocr_result"`
	Status        *string    `gorm:"column:status;default:pending" json:"status"`
	CreatedAt     *time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     *time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName ImageOcrTask's table name
func (*ImageOcrTask) TableName() string {
	return TableNameImageOcrTask
}
