// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQuestionKnowledgePoint = "question_knowledge_point"

// QuestionKnowledgePoint mapped from table <question_knowledge_point>
type QuestionKnowledgePoint struct {
	ID               int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	QuestionID       int32      `gorm:"column:question_id;not null" json:"question_id"`
	KnowledgePointID int32      `gorm:"column:knowledge_point_id;not null" json:"knowledge_point_id"`
	CreatedAt        *time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName QuestionKnowledgePoint's table name
func (*QuestionKnowledgePoint) TableName() string {
	return TableNameQuestionKnowledgePoint
}
